spring.application.name=backendPortafolio
spring.threads.virtual.enabled=true
spring.profiles.active=${ACTIVE_PROFILE:test}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
